### PR TITLE
Clean up comparison notebooks and fix vis.py

### LINKED ISSUE #92: knoten does not ship vis
I installed knoten with the command:

conda install -c usgs-astrogeology -c conda-forge knoten

in a fresh environment having no other packages. Then started the python from this very environment, and did 

import knoten

So far so good.

Then I did

from knoten import vis

I got the error: 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'vis'

However,  this works:

from knoten import csmapi 

Is there a reason why vis is missing from the packaged knoten? It appears to be in the repo, and if I pulled it manually it works (kind of, some apis are broken when it comes to plotly).

### LINKED ISSUE #123: CI, Python Versioning, and ISIS
This issue relates to the use of `pysis` in the library. When adding CI (#122) we saw that builds with python >=3.10 were consistently failing to solve using mamba/conda. The issue is that the `pysis` library is pinned to have an isis dependency. That dependency needs ISIS installed.

To get CI running `pysis` was swapped for `kalasiris`, which does not have a python pinning. `kalasiris` assumes that the `ISISROOT` and `ISISDATA` env variables are set. Therefore ISIS can live in a different environment.

I doubt that the swap to `kalasiris` is particularly contentious as the library has a [`pysis` style interface](https://kalasiris.readthedocs.io/en/latest/kalasiris.html#module-kalasiris.pysis) that is a straight swap in. What I think warrants more discussion is the now implicit ISIS dependency if anyone wants to use the `vis` module or run and of the comparison notebooks. Do these notebooks belong in `knoten` or are they an example consuming `knoten`? Should the notebooks include a README style entry at the top instructing users to install ISIS in a different environment AND add the necessary `os.environ` lines?

### PR DESCRIPTION
**Pull request by amystamile-usgs**
When cleaning up the comparison notebooks, incorporating the newer ALE implementation essentially standardized the code across all the comparison notebooks. Therefore, I decided it would be more efficient to maintain a single comparison notebook. 

closes #108, closes #92, closes #123 

I also noticed that vis.py dependencies were not being shipped in the knoten releases (kalasiris and plotly).

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Review by jlaura — APPROVED** [review]
LGTM - do you want to strip the output cells from the notebooks? Then the notebook won't have those big binary blobs. The downside is that someone has to run the notebook to see the visualization output. Whatever is cool here!

**Comment by jlaura** [comment]
Ohh also, kalasiris dependency - can that be optional? Honestly, can all of the vis stuff be optional? For someone not wanting to do a comparison, they are bloat in a CSM library.

**Comment by amystamile-usgs** [comment]
> Ohh also, kalasiris dependency - can that be optional? Honestly, can all of the vis stuff be optional? For someone not wanting to do a comparison, they are bloat in a CSM library.

Maybe not including vis.py dependencies was intentional. I think it would be a good idea not to ship kalasiris with knoten. I can just add instructions to install it in the notebook.

**Review by jlaura — APPROVED** [review]

**Comment by jlaura** [comment]
LGTM!
